### ISSUE TITLE
Unable to resolve the dependency

### ISSUE THREAD

**Issue by addyi** [chRyNaN/uri#4]
As far as I can see the dependency is not resolvable anymore from repsy.io: https://repo.repsy.io/mvn/chrynan/public/com/chrynan/uri/uri-core/0.4.0/uri-core-0.4.0.pom

Status of repsy itself seems to be 100%: https://status.repsy.io/

I can reproduce this resolve issue on two different CIs and my local machine so I would assume it is not just me.

**Comment by addyi** [comment]
We reached out to repsy.io via email, and they responded, indicating that they would investigate the issue.

Fortunately, the dependency is now available again! \o/ We're unsure if the fix was due to their intervention or if it resolved on its own. I will post here if we here back from them.

**Comment by chRyNaN** [comment]
Thank you for pointing this out and clearing it up. I haven't had the time lately to devote to many of my open source projects.

**Comment by addyi** [comment]
@chRyNaN No problem. I know it his hard to donate time when you also need a healthy work life balance. Thank you for your work 🙇
